name: en_words
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.1
  zoom_tap_animation: ^1.1.0
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.3
  mask_text_input_formatter: ^2.5.0
  curved_navigation_bar: ^1.0.3
  lottie: ^2.6.0
  dio: ^5.3.2
  sqflite: ^2.3.0
  image_picker: ^1.0.4
  pinput: ^3.0.1
  equatable: ^2.0.5
  url_launcher: ^6.1.14
  flutter_linkify: ^6.0.0
  shimmer: ^3.0.0
  get: ^4.6.5
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
